# Generated by Django 6.0.3 on 2026-05-18 00:41

import apps.common.utils.media_layout
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_spaces', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('client_approved', 'Solicitud aprobada'), ('invoiced', 'Facturada'), ('paid', 'Pagada'), ('art_approved', 'Arte aprobado'), ('permit_pending', 'Permiso alcaldía'), ('installation', 'Instalación'), ('active', 'Activa'), ('expired', 'Vencida'), ('cancelled', 'Cancelada')], default='draft', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Sin indicar'), ('card', 'Tarjeta'), ('bank_transfer', 'Transferencia bancaria'), ('mobile_payment', 'Pago móvil'), ('zelle', 'Zelle'), ('crypto', 'Cripto'), ('cash', 'Efectivo'), ('other', 'Otro')], db_index=True, default='', max_length=32)),
                ('payment_receipt', models.FileField(blank=True, help_text='Comprobante subido por el cliente en checkout (media/<slug>/orders/receipts/…; histórico: orders/receipts/…).', null=True, upload_to=apps.common.utils.media_layout.order_payment_receipt_upload)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Código único de pedido (#SLUG-ORDER-000001). Se asigna al crear.', max_length=64, null=True, unique=True)),
                ('payment_conditions', models.TextField(blank=True, default='', help_text='Condiciones de pago (hoja de negociación).')),
                ('negotiation_observations', models.TextField(blank=True, default='', help_text='Observaciones en hoja de negociación (líneas del pedido, texto libre).')),
                ('negotiation_sheet_pdf', models.FileField(blank=True, help_text='Hoja de negociación generada al aprobar la solicitud (histórico: orders/generated/…).', null=True, upload_to=apps.common.utils.media_layout.order_generated_document_upload)),
                ('municipality_authorization_pdf', models.FileField(blank=True, help_text='Carta de autorización para trámite en alcaldía (histórico: orders/generated/…).', null=True, upload_to=apps.common.utils.media_layout.order_generated_document_upload)),
                ('invoice_pdf', models.FileField(blank=True, help_text='Factura PDF generada al marcar como facturada (histórico: orders/generated/…).', null=True, upload_to=apps.common.utils.media_layout.order_generated_document_upload)),
                ('negotiation_sheet_signed', models.FileField(blank=True, help_text='Hoja de negociación firmada por el cliente (histórico: orders/signed/…).', null=True, upload_to=apps.common.utils.media_layout.order_signed_document_upload)),
                ('invoice_number', models.CharField(blank=True, default='', help_text='Número o referencia de factura (opcional, en PDF).', max_length=64)),
                ('installation_verified_at', models.DateTimeField(blank=True, help_text='Cuando mercadeo del CC validó la instalación conforme.', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderInstallationPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('mounting_date', models.DateField()),
                ('installation_company_name', models.CharField(max_length=255)),
                ('staff_members', models.JSONField(default=list, help_text='Lista: [{"full_name": "...", "id_number": "V-12345678"}]')),
                ('notes', models.TextField(blank=True, default='')),
                ('municipal_reference', models.CharField(blank=True, default='', help_text='Referencia o expediente municipal si aplica.', max_length=255)),
                ('request_pdf', models.FileField(blank=True, help_text='PDF generado al enviar la solicitud (media/<slug>/orders/installation_permits/…; histórico: orders/installation_permits/…).', null=True, upload_to=apps.common.utils.media_layout.order_installation_permit_pdf_upload)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_permit', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ad_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='ad_spaces.adspace')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderArtAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('file', models.FileField(help_text='Arte adjunto (media/<slug>/orders/arts/…; histórico: orders/arts/…).', upload_to=apps.common.utils.media_layout.order_art_attachment_upload)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_attachments', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Línea del pedido (toma) a la que aplica el archivo; obligatorio si el pedido tiene varias líneas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_attachments', to='orders.orderitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
