# Generated by Django 6.0.3 on 2026-05-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderinstallationpermit_municipal_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('client_approved', 'Solicitud aprobada'), ('art_approved', 'Arte aprobado'), ('invoiced', 'Facturada'), ('paid', 'Pagada'), ('permit_pending', 'Permiso alcaldía'), ('installation', 'Instalación'), ('active', 'Activa'), ('expired', 'Vencida'), ('cancelled', 'Rechazada')], default='draft', max_length=32),
        ),
    ]
