# Generated by Django 6.0.3 on 2026-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_original_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Importe acordado para esta toma (puede ser menor que el catálogo).', max_digits=12),
        ),
    ]
