# Generated by Django 6.0.3 on 2026-06-12 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentinstallment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).'),
        ),
        migrations.AlterField(
            model_name='orderpaymentinstallment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderpaymentplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).'),
        ),
        migrations.AlterField(
            model_name='orderpaymentplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
