# Generated by Django 6.1.1 on 2026-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_margarita_disable_iva_open_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('client_approved', 'Solicitud aprobada'), ('art_approved', 'Arte aprobado'), ('invoiced', 'Facturada'), ('paid', 'Pagada'), ('permit_pending', 'Permiso alcaldía'), ('installation', 'Instalación'), ('active', 'Activa'), ('expired', 'Finalizada'), ('cancelled', 'Rechazada')], default='draft', max_length=32),
        ),
    ]
