# Generated by Django 6.1.1 on 2026-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_status_finalizada_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='early_end_note',
            field=models.TextField(blank=True, default='', help_text='Motivo de la finalización anticipada.'),
        ),
        migrations.AddField(
            model_name='order',
            name='early_end_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reembolso registrado al finalizar un pago completo. Vacío si no aplica.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ended_early',
            field=models.BooleanField(default=False, help_text='El admin cerró el contrato antes de la fecha de fin.'),
        ),
    ]
