# Generated by Django 6.1.1 on 2026-10-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_early_end_note_order_early_end_refund_amount_and_more'),
        ('workspaces', '0008_workspace_rif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_submitted', 'Pedido nuevo'), ('competing_bid', 'Puja'), ('negotiation_signed', 'Hoja firmada'), ('art_uploaded', 'Arte cargado'), ('payment_receipt', 'Comprobante de pago'), ('hold_expiring', 'Reserva por vencer'), ('hold_expired', 'Reserva vencida'), ('contract_running', 'Contrato en curso'), ('contract_ending_soon', 'Por finalizar'), ('contract_finished', 'Contrato finalizado'), ('contract_ended_early', 'Finalización anticipada')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=280)),
                ('href', models.CharField(max_length=300)),
                ('dedupe_key', models.CharField(max_length=160)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='orders_admi_recipie_b0f985_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='orders_admin_notification_recipient_dedupe')],
            },
        ),
    ]
