# Generated by Django 6.0.3 on 2026-05-18 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_spaces', '0002_alter_adspace_code'),
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('start_date', models.DateField(help_text='Inicio del período de alquiler en disputa.')),
                ('end_date', models.DateField(help_text='Fin del período de alquiler en disputa.')),
                ('opens_at', models.DateTimeField(help_text='Momento en que se aceptan ofertas.')),
                ('closes_at', models.DateTimeField(help_text='Cierre de la recepción de ofertas.')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierta'), ('closed', 'Cerrada'), ('awarded', 'Adjudicada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20)),
                ('minimum_bid_usd', models.DecimalField(decimal_places=2, help_text='Oferta mínima inicial (USD).', max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('ad_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='ad_spaces.adspace')),
                ('order', models.ForeignKey(blank=True, help_text='Pedido generado al adjudicar la puja.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_auctions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Puja de toma',
                'verbose_name_plural': 'Pujas de tomas',
                'ordering': ['-closes_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SpaceBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bidding.spaceauction')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='space_bids', to='clients.client')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-amount_usd', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='spaceauction',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bidding.spacebid'),
        ),
    ]
