# Generated by Django 6.0.3 on 2026-05-18 00:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('reserved', 'Reserved'), ('occupied', 'Occupied'), ('blocked', 'Blocked')], max_length=20)),
                ('ad_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='ad_spaces.adspace')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
