# Generated by Django 6.0.3 on 2026-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_availabilityblock_note_and_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityblock',
            name='type',
            field=models.CharField(choices=[('reserved', 'Reservado'), ('occupied', 'Ocupado'), ('blocked', 'Bloqueado')], max_length=20),
        ),
    ]
