# Generated by Django 6.0.3 on 2026-05-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0004_availabilityblock_occupied_expired_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityblock',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Motivo interno (mantenimiento, reserva manual, etc.).', max_length=500),
        ),
    ]
