# Generated by Django 6.0.3 on 2026-05-18 00:41

import apps.common.utils.media_layout
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('code', models.CharField(db_index=True, help_text='Código único de la toma: prefijo-T{número}[sufijo], ej. SCC-T1, SLC-T1A (el prefijo no depende del centro).', max_length=32, unique=True)),
                ('type', models.CharField(choices=[('billboard', 'Valla (genérico)'), ('banner', 'Banner / pendón (genérico)'), ('elevator', 'Ascensor'), ('other', 'Otro'), ('valla_vertical', 'Valla vertical / gigantografía vertical'), ('valla_horizontal', 'Valla horizontal / gigantografía horizontal'), ('gigantografia_fachada', 'Gigantografía en fachada'), ('pendon_balcon', 'Pendón de balcón'), ('pendon_atrio', 'Pendón de atrio / colgante central'), ('pendon_pasillo', 'Pendón de pasillo'), ('pendon_plaza', 'Pendón de plaza'), ('pendon_columna', 'Pendón de columna')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('location_description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=64)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('occupied', 'Ocupado'), ('blocked', 'Bloqueado')], default='available', max_length=20)),
                ('cover_image', models.ImageField(blank=True, help_text='Copia de la primera imagen de galería; media/<slug>/spaces/covers/AÑO/MES/ (histórico: spaces/covers/…). La galería va en spaces/gallery/….', null=True, upload_to=apps.common.utils.media_layout.ad_space_cover_upload)),
                ('venue_zone', models.CharField(blank=True, max_length=255)),
                ('double_sided', models.BooleanField(default=False)),
                ('production_specs', models.TextField(blank=True)),
                ('installation_notes', models.TextField(blank=True)),
                ('hem_pocket_top_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Hueco superior tipo bolsillo (ej. 4,5 cm en pendones balcón).', max_digits=4, null=True)),
                ('shopping_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_spaces', to='malls.shoppingcenter')),
            ],
            options={
                'ordering': ['shopping_center', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AdSpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Galería de la toma: media/<slug>/spaces/gallery/AÑO/MES/ (histórico: spaces/gallery/…).', upload_to=apps.common.utils.media_layout.ad_space_gallery_upload)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('ad_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='ad_spaces.adspace')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
