# Generated by Django 6.0.3 on 2026-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspace',
            name='code',
            field=models.CharField(db_index=True, help_text='Código único de la toma: prefijo-T{número}[sufijo], ej. DEMO-T1, CC-T2A (el prefijo no depende del centro).', max_length=32, unique=True),
        ),
    ]
