# Generated by Django 6.0.3 on 2026-05-31 17:00

import apps.common.utils.media_layout
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

LEGACY_TYPE_LABELS = {
    "billboard": "Valla (genérico)",
    "banner": "Banner / pendón (genérico)",
    "elevator": "Ascensor",
    "other": "Otro",
    "valla_vertical": "Valla vertical / gigantografía vertical",
    "valla_horizontal": "Valla horizontal / gigantografía horizontal",
    "gigantografia_fachada": "Gigantografía en fachada",
    "pendon_balcon": "Pendón de balcón",
    "pendon_atrio": "Pendón de atrio / colgante central",
    "pendon_pasillo": "Pendón de pasillo",
    "pendon_plaza": "Pendón de plaza",
    "pendon_columna": "Pendón de columna",
}


def forwards_migrate_formats(apps, schema_editor):
    AdSpace = apps.get_model("ad_spaces", "AdSpace")
    AdSpaceProductType = apps.get_model("ad_spaces", "AdSpaceProductType")
    AdSpaceFormat = apps.get_model("ad_spaces", "AdSpaceFormat")
    ShoppingCenter = apps.get_model("malls", "ShoppingCenter")

    type_cache: dict[tuple[int, str], int] = {}

    def product_type_id_for(workspace_id: int, legacy_type: str) -> int:
        slug = (legacy_type or "other").strip().lower() or "other"
        key = (workspace_id, slug)
        if key in type_cache:
            return type_cache[key]
        label = LEGACY_TYPE_LABELS.get(slug, slug.replace("_", " ").title())
        row, _ = AdSpaceProductType.objects.get_or_create(
            workspace_id=workspace_id,
            slug=slug,
            defaults={"name": label},
        )
        type_cache[key] = row.pk
        return row.pk

    for space in AdSpace.objects.select_related("shopping_center").iterator():
        center = space.shopping_center
        if center is None:
            continue
        ws_id = center.workspace_id
        if ws_id is None:
            continue
        legacy_type = getattr(space, "type", None) or "other"
        pt_id = product_type_id_for(ws_id, legacy_type)
        loc_parts = [
            getattr(space, "location_description", "") or "",
            getattr(space, "venue_zone", "") or "",
            getattr(space, "level", "") or "",
        ]
        location = " · ".join(p.strip() for p in loc_parts if p and str(p).strip())
        AdSpaceFormat.objects.create(
            ad_space_id=space.pk,
            product_type_id=pt_id,
            width=getattr(space, "width", None),
            height=getattr(space, "height", None),
            quantity=getattr(space, "quantity", None) or 1,
            location=location,
            double_sided=bool(getattr(space, "double_sided", False)),
            sort_order=0,
        )


def backwards_migrate_formats(apps, schema_editor):
    AdSpaceFormat = apps.get_model("ad_spaces", "AdSpaceFormat")
    AdSpaceFormat.objects.all().delete()
    AdSpaceProductType = apps.get_model("ad_spaces", "AdSpaceProductType")
    AdSpaceProductType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ad_spaces", "0004_remove_reserved_ad_space_status"),
        ("workspaces", "0006_alter_workspace_transactional_email_from_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adspace",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="adspace",
            name="location_image",
            field=models.ImageField(
                blank=True,
                help_text="Plano o foto de ubicación del espacio.",
                null=True,
                upload_to=apps.common.utils.media_layout.ad_space_location_image_upload,
            ),
        ),
        migrations.AddField(
            model_name="adspace",
            name="production_image",
            field=models.ImageField(
                blank=True,
                help_text="Referencia de arte y producción.",
                null=True,
                upload_to=apps.common.utils.media_layout.ad_space_production_image_upload,
            ),
        ),
        migrations.CreateModel(
            name="AdSpaceProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="Si está desmarcado, el registro se considera inactivo (no borrado).")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=64)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ad_space_product_types", to="workspaces.workspace")),
            ],
            options={
                "ordering": ["name", "slug"],
            },
        ),
        migrations.CreateModel(
            name="AdSpaceFormat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("width", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("height", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("location", models.TextField(blank=True, default="")),
                ("double_sided", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("ad_space", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="formats", to="ad_spaces.adspace")),
                ("product_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="space_formats", to="ad_spaces.adspaceproducttype")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="adspaceproducttype",
            constraint=models.UniqueConstraint(fields=("workspace", "slug"), name="ad_spaces_product_type_workspace_slug_uniq"),
        ),
        migrations.RunPython(forwards_migrate_formats, backwards_migrate_formats),
        migrations.RemoveField(model_name="adspace", name="double_sided"),
        migrations.RemoveField(model_name="adspace", name="height"),
        migrations.RemoveField(model_name="adspace", name="hem_pocket_top_cm"),
        migrations.RemoveField(model_name="adspace", name="installation_notes"),
        migrations.RemoveField(model_name="adspace", name="level"),
        migrations.RemoveField(model_name="adspace", name="location_description"),
        migrations.RemoveField(model_name="adspace", name="material"),
        migrations.RemoveField(model_name="adspace", name="production_specs"),
        migrations.RemoveField(model_name="adspace", name="quantity"),
        migrations.RemoveField(model_name="adspace", name="type"),
        migrations.RemoveField(model_name="adspace", name="venue_zone"),
        migrations.RemoveField(model_name="adspace", name="width"),
        migrations.AlterField(
            model_name="adspace",
            name="code",
            field=models.CharField(db_index=True, help_text="Código único de la toma: prefijo-T{número}[sufijo], ej. DEMO-T1, CC-T2A.", max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="adspace",
            name="cover_image",
            field=models.ImageField(blank=True, help_text="Copia de la primera imagen de galería (portada).", null=True, upload_to=apps.common.utils.media_layout.ad_space_cover_upload),
        ),
        migrations.AlterField(
            model_name="adspaceimage",
            name="image",
            field=models.ImageField(upload_to=apps.common.utils.media_layout.ad_space_gallery_upload),
        ),
    ]
