# Generated by Django 6.0.3 on 2026-06-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_spaces', '0006_rename_adspace_status_to_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspace',
            name='availability',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupado'), ('blocked', 'Bloqueado')], default='available', help_text='Disponibilidad comercial (disponible, ocupado o bloqueado manualmente).', max_length=20),
        ),
    ]
