# Generated by Django 6.0.3 on 2026-05-17 23:49

import apps.common.utils.media_layout
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Identificador en URL pública (?center=, detalle /api/catalog/centers/{slug}/). Único por workspace.', max_length=80)),
                ('city', models.CharField(max_length=120)),
                ('district', models.CharField(blank=True, help_text='Zona o urbanización para el titular de la tarjeta en portada (ej. Chacao).', max_length=120)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, default='Venezuela', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Portada del centro: media/<slug>/centers/covers/AÑO/MES/ (histórico: centers/covers/…).', null=True, upload_to=apps.common.utils.media_layout.shopping_center_cover_upload)),
                ('on_homepage', models.BooleanField(db_index=True, default=True, help_text='Si se incluye en el listado público GET /api/centers/ (la portada del sitio lista tomas).')),
                ('listing_order', models.PositiveSmallIntegerField(default=0, help_text='Orden en ese listado de centros (menor primero).')),
                ('marketplace_catalog_enabled', models.BooleanField(db_index=True, default=False, help_text='Si el catálogo público de tomas está habilitado para este centro (reservas en marketplace).')),
                ('lessor_legal_name', models.CharField(blank=True, default='', help_text='Razón social del arrendador (Constructora Acme, C.A., etc.).', max_length=255)),
                ('lessor_rif', models.CharField(blank=True, default='', help_text='RIF del arrendador en documentos legales.', max_length=32)),
                ('municipal_authority_line', models.CharField(blank=True, default='', help_text='Destinatario carta municipio, ej. «Sres. Alcaldía Municipio Chacao».', max_length=255)),
                ('municipal_permit_notice', models.TextField(blank=True, default='', help_text='Aviso en catálogo: el cliente debe gestionar permiso municipal.')),
                ('advertising_regulations', models.TextField(blank=True, default='', help_text='Normativas de uso de tomas publicitarias (HTML o texto plano).')),
                ('authorization_letter_city', models.CharField(blank=True, default='Caracas', help_text='Ciudad en el encabezado de fecha de la carta al municipio.', max_length=120)),
                ('workspace', models.ForeignKey(help_text='Owner / tenant al que pertenece este centro comercial.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_centers', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['listing_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCenterMountingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('rif', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('shopping_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounting_providers', to='malls.shoppingcenter')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shoppingcenter',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='malls_shoppingcenter_workspace_slug_uniq'),
        ),
    ]
