# Generated by Django 6.0.3 on 2026-05-18 14:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0002_shoppingcenter_high_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcenter',
            name='high_season_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Factor sobre el canon mensual en meses de temporada alta (1.25 = +25 %).', max_digits=5),
        ),
    ]
