# Generated by Django 6.0.3 on 2026-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malls', '0008_rental_billing_calendar_month_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcenter',
            name='high_season_months',
            field=models.JSONField(blank=True, default=list, help_text='Meses con canon +30 %: Margarita jul–ago y nov–dic; resto nov–dic. Se asignan al guardar según nombre/slug del centro.'),
        ),
    ]
