# Generated by Django 6.0.3 on 2026-05-17 23:49

import apps.common.utils.media_layout
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador marketplace'), ('client', 'Cliente marketplace')], db_index=True, default='client', max_length=16)),
                ('cover_image', models.ImageField(blank=True, help_text='Foto de perfil: media/<slug>/users/covers/AÑO/MES/ (histórico: covers/users/…).', null=True, upload_to=apps.common.utils.media_layout.user_profile_cover_upload)),
                ('client', models.ForeignKey(blank=True, help_text='Empresa que este usuario representa (como mucho una). Obligatorio si el rol es cliente marketplace. Varios usuarios pueden compartir la misma empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='clients.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Administrador marketplace: obligatorio (owner del panel). Cliente marketplace: obligatorio y debe ser el workspace de la empresa vinculada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
