# Generated by Django 6.0.3 on 2026-05-18 00:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malls', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('rif', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('shopping_centers', models.ManyToManyField(blank=True, help_text='Centros donde este proveedor está autorizado.', related_name='mounting_providers', to='malls.shoppingcenter')),
                ('workspace', models.ForeignKey(help_text='Owner / tenant al que pertenece este proveedor.', on_delete=django.db.models.deletion.CASCADE, related_name='mounting_providers', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'company_name'), name='providers_mountingprovider_workspace_company_uniq')],
            },
        ),
    ]
