# Generated by Django 6.0.3 on 2026-05-18 00:41

import apps.common.utils.media_layout
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('slug', models.SlugField(help_text='Identificador estable para subdominio y APIs (solo letras minúsculas, números, guiones).', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Nombre comercial del owner (marca operadora del marketplace).', max_length=200)),
                ('legal_name', models.CharField(blank=True, help_text='Razón social u organismo propietario (opcional).', max_length=255)),
                ('logo', models.FileField(blank=True, help_text='Marca completa con tipografía (logotipo). Cabecera amplia, pie, emails. Formatos: SVG, PNG, JPEG, GIF o WebP. Almacenamiento bajo media/<slug>/workspaces/logos/…', null=True, upload_to=apps.common.utils.media_layout.workspace_brand_logo_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('svg', 'png', 'jpg', 'jpeg', 'gif', 'webp'), message='Formato no admitido. Usa SVG, PNG, JPEG, GIF o WebP.')], verbose_name='Logo (logotipo completo)')),
                ('logo_mark', models.FileField(blank=True, help_text='Símbolo o marca reducida sin el nombre extendido (header compacto, favicon si no subes uno aparte). Mismos formatos que el logo. media/<slug>/workspaces/logo_marks/…', null=True, upload_to=apps.common.utils.media_layout.workspace_brand_logo_mark_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('svg', 'png', 'jpg', 'jpeg', 'gif', 'webp'), message='Formato no admitido. Usa SVG, PNG, JPEG, GIF o WebP.')], verbose_name='Isotipo')),
                ('favicon', models.FileField(blank=True, help_text='Icono de pestaña del navegador. SVG, PNG, ICO, JPEG, GIF o WebP. media/<slug>/workspaces/favicons/…', null=True, upload_to=apps.common.utils.media_layout.workspace_brand_favicon_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico'), message='Formato no admitido. Usa SVG, PNG, ICO, JPEG, GIF o WebP.')], verbose_name='Favicon')),
                ('logo_png_artifacts', models.FileField(blank=True, help_text='Solo PNG. Se usa en correos transaccionales y PDFs del pedido donde no aplica SVG. Opcional si ya subes mapas de bits en logotipo/isotipo; recomendado si solo usas SVG en marca. media/<slug>/workspaces/logo_png_artifacts/…', null=True, upload_to=apps.common.utils.media_layout.workspace_brand_logo_png_artifacts_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png',), message='Formato no admitido. Usa solo PNG.')], verbose_name='Logo PNG (correo, PDF y similares)')),
                ('primary_color', models.CharField(blank=True, help_text='Hex (ej. #2c2c81). Tema y acentos del marketplace.', max_length=32, verbose_name='Color primario')),
                ('secondary_color', models.CharField(blank=True, help_text='Hex. Acentos secundarios (ej. badges, CTAs alternos).', max_length=32, verbose_name='Color secundario')),
                ('support_email', models.EmailField(blank=True, help_text='Contacto público del operador (p. ej. pie de página o avisos).', max_length=254, verbose_name='Correo de soporte')),
                ('phone', models.CharField(blank=True, help_text='Contacto telefónico público del operador (opcional).', max_length=32, verbose_name='Teléfono')),
                ('country', models.CharField(blank=True, help_text='País de la sede o operación del owner (opcional).', max_length=120, verbose_name='País')),
                ('city', models.CharField(blank=True, help_text='Ciudad de la sede o operación del owner (opcional).', max_length=120, verbose_name='Ciudad')),
                ('marketplace_title', models.CharField(blank=True, help_text='Nombre corto que ve el visitante (si está vacío, se usa el nombre del workspace).', max_length=120, verbose_name='Título del marketplace')),
                ('marketplace_tagline', models.CharField(blank=True, help_text='Frase corta opcional (propuesta de valor). Sale en la API pública; la interfaz del marketplace aún puede no mostrarla hasta conectarla en el front.', max_length=255, verbose_name='Eslogan / subtítulo')),
                ('catalog_scc_seeded_at', models.DateTimeField(blank=True, db_index=True, help_text='Si está definido, el comando seed_production_catalog ya importó tomas SCC para este owner.', null=True)),
                ('catalog_slc_seeded_at', models.DateTimeField(blank=True, db_index=True, help_text='Si está definido, el comando seed_production_catalog ya importó tomas SLC para este owner.', null=True)),
                ('can_create_shopping_centers', models.BooleanField(default=True, help_text='Si está desactivado, el panel no permite crear CCs (API y UI).', verbose_name='Puede crear centros comerciales')),
                ('can_create_ad_spaces', models.BooleanField(default=True, help_text='Si está desactivado, el panel no permite crear tomas / espacios publicitarios.', verbose_name='Puede crear tomas')),
                ('can_create_marketplace_admin_users', models.BooleanField(default=True, help_text='Si está desactivado, no se pueden crear ni promover usuarios con rol administrador del panel.', verbose_name='Puede crear administradores marketplace')),
                ('transactional_email_host', models.CharField(blank=True, help_text='Ej. smtp.gmail.com. Si está vacío, no se envían correos automáticos de pedidos con esta cuenta.', max_length=255, verbose_name='Servidor SMTP (envío de notificaciones)')),
                ('transactional_email_port', models.PositiveIntegerField(default=587, verbose_name='Puerto SMTP')),
                ('transactional_email_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS al conectar al SMTP')),
                ('transactional_email_use_ssl', models.BooleanField(default=False, help_text='Conexión cifrada desde el inicio (típico en puerto 465). No combinar con STARTTLS en el mismo servidor.', verbose_name='SSL implícito al conectar al SMTP')),
                ('transactional_email_username', models.CharField(blank=True, max_length=255, verbose_name='Usuario SMTP')),
                ('transactional_email_password', models.CharField(blank=True, help_text='Se guarda en base de datos; restringe acceso al servidor y usa contraseña de aplicación si aplica.', max_length=512, verbose_name='Contraseña SMTP')),
                ('transactional_email_from_address', models.EmailField(blank=True, help_text='Correo que verán admin y cliente en notificaciones de pedidos.', max_length=254, verbose_name='Dirección remitente (From)')),
                ('transactional_email_from_name', models.CharField(blank=True, help_text='Ej. nombre del marketplace; si está vacío se usa el nombre comercial del workspace.', max_length=120, verbose_name='Nombre remitente (opcional)')),
                ('transactional_email_method', models.CharField(blank=True, default='smtp', help_text='smtp: credenciales SMTP del formulario; api: relay por API key (Mailgun u otros en el futuro).', max_length=20, verbose_name='Método de envío transaccional')),
                ('transactional_email_provider', models.CharField(blank=True, default='', help_text='Proveedor de relay por API key. Por ahora: mailgun.', max_length=40, verbose_name='Proveedor API (si method=api)')),
                ('transactional_email_api_key', models.CharField(blank=True, default='', help_text='Se guarda en base de datos. Mantener vacío para conservar la clave ya guardada.', max_length=255, verbose_name='API key (si method=api)')),
                ('transactional_email_mailgun_domain', models.CharField(blank=True, default='', help_text='Dominio verificado en Mailgun, ej. mg.tudominio.com.', max_length=255, verbose_name='Mailgun domain')),
                ('transactional_email_mailgun_region', models.CharField(blank=True, default='us', help_text='Región de Mailgun: us o eu (define el endpoint).', max_length=10, verbose_name='Mailgun region')),
                ('catalog_seed_feeder', models.ForeignKey(blank=True, help_text='Primer usuario administrador marketplace de este workspace (referencia de carga de catálogo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace (owner)',
                'verbose_name_plural': 'Workspaces (owners)',
                'ordering': ['slug'],
            },
        ),
    ]
