# Generated by Django 6.0.3 on 2026-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_generic_catalog_seed_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='marketplace_bidding_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo, el operador puede publicar pujas por toma y los clientes pueden ofertar.', verbose_name='Pujas en marketplace'),
        ),
    ]
