# Generated by Django 6.0.3 on 2026-05-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_remove_workspace_marketplace_bidding_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='transactional_email_from_address',
            field=models.EmailField(blank=True, help_text='Correo que verán administradores y la empresa en notificaciones de pedidos.', max_length=254, verbose_name='Dirección remitente (From)'),
        ),
    ]
