# Generated by Django 6.0.3 on 2026-05-18 00:41

import apps.common.utils.media_layout
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_spaces', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('company_name', models.CharField(max_length=255)),
                ('rif', models.CharField(blank=True, help_text='Identificación fiscal; se puede completar después en Mi empresa.', max_length=32, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('representative_name', models.CharField(blank=True, help_text='Representante legal o firmante (hoja de negociación, cartas).', max_length=255)),
                ('representative_id_number', models.CharField(blank=True, help_text='Cédula de identidad del representante (ej. V-17.311.805).', max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido')], default='active', max_length=20)),
                ('cover_image', models.ImageField(blank=True, help_text='Portada de empresa: media/<slug>/clients/covers/AÑO/MES/ (histórico: covers/clients/…).', null=True, upload_to=apps.common.utils.media_layout.client_cover_upload)),
                ('workspace', models.ForeignKey(help_text='Tenant al que pertenece la empresa cliente (RIF único por workspace cuando está indicado).', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientAdSpaceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está desmarcado, el registro se considera inactivo (no borrado).')),
                ('ad_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_favorites', to='ad_spaces.adspace')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_space_favorites', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('workspace', 'rif'), name='clients_client_workspace_rif_uniq'),
        ),
        migrations.AddConstraint(
            model_name='clientadspacefavorite',
            constraint=models.UniqueConstraint(fields=('client', 'ad_space'), name='clients_favorite_client_ad_space_uniq'),
        ),
    ]
